/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Ajouter (void);
GtkWidget* create_interface (void);
GtkWidget* create_ahmed_supprimer (void);
GtkWidget* create_Modification (void);
GtkWidget* create_fenetre_captdeff (void);
