/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Ajouter (void)
{
  GtkWidget *Ajouter;
  GtkWidget *fixed1;
  GtkWidget *entry_reference_GestCapt;
  GtkWidget *entry_Localisation_GestCapt;
  GtkWidget *entry_Valeur_Min_GestCapt;
  GtkWidget *entry_Valeur_Max_GestCapt;
  GtkWidget *image19;
  GtkWidget *label4;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *ahmed_combobox1;
  GtkWidget *label5;
  GtkWidget *label12;
  GtkWidget *label11;
  GtkWidget *ahmed_radio_1;
  GSList *ahmed_radio_1_group = NULL;
  GtkWidget *ahmed_raddio_0;
  GtkWidget *button_Ajout_Annuler_GestCapt;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label30;
  GtkWidget *button_Ajout_Ajouter_GestCapt;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label7;

  Ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Ajouter, 750, 500);
  gtk_window_set_title (GTK_WINDOW (Ajouter), _("Ajouter"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Ajouter), fixed1);
  gtk_widget_set_size_request (fixed1, 612, 360);

  entry_reference_GestCapt = gtk_entry_new ();
  gtk_widget_show (entry_reference_GestCapt);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_reference_GestCapt, 152, 88);
  gtk_widget_set_size_request (entry_reference_GestCapt, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_reference_GestCapt), 8226);

  entry_Localisation_GestCapt = gtk_entry_new ();
  gtk_widget_show (entry_Localisation_GestCapt);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_Localisation_GestCapt, 152, 216);
  gtk_widget_set_size_request (entry_Localisation_GestCapt, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Localisation_GestCapt), 8226);

  entry_Valeur_Min_GestCapt = gtk_entry_new ();
  gtk_widget_show (entry_Valeur_Min_GestCapt);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_Valeur_Min_GestCapt, 512, 88);
  gtk_widget_set_size_request (entry_Valeur_Min_GestCapt, 100, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Valeur_Min_GestCapt), 8226);

  entry_Valeur_Max_GestCapt = gtk_entry_new ();
  gtk_widget_show (entry_Valeur_Max_GestCapt);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_Valeur_Max_GestCapt, 512, 160);
  gtk_widget_set_size_request (entry_Valeur_Max_GestCapt, 100, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Valeur_Max_GestCapt), 8226);

  image19 = create_pixmap (Ajouter, "455.png");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed1), image19, 0, 0);
  gtk_widget_set_size_request (image19, 750, 500);

  label4 = gtk_label_new (_("Valeur Min"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 408, 88);
  gtk_widget_set_size_request (label4, 100, 30);

  label2 = gtk_label_new (_("R\303\251ference "));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 40, 88);
  gtk_widget_set_size_request (label2, 100, 30);

  label3 = gtk_label_new (_("Type"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 32, 152);
  gtk_widget_set_size_request (label3, 100, 30);

  ahmed_combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (ahmed_combobox1);
  gtk_fixed_put (GTK_FIXED (fixed1), ahmed_combobox1, 136, 152);
  gtk_widget_set_size_request (ahmed_combobox1, 72, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (ahmed_combobox1), _("Temperature"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ahmed_combobox1), _("Gaz"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ahmed_combobox1), _("Humidite"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ahmed_combobox1), _("Fumer"));

  label5 = gtk_label_new (_("Valeur Max"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 408, 160);
  gtk_widget_set_size_request (label5, 100, 30);

  label12 = gtk_label_new (_("Etat"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed1), label12, 400, 216);
  gtk_widget_set_size_request (label12, 100, 30);

  label11 = gtk_label_new (_("Localisation"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed1), label11, 48, 216);
  gtk_widget_set_size_request (label11, 100, 30);

  ahmed_radio_1 = gtk_radio_button_new_with_mnemonic (NULL, _("etat 1"));
  gtk_widget_show (ahmed_radio_1);
  gtk_fixed_put (GTK_FIXED (fixed1), ahmed_radio_1, 464, 256);
  gtk_widget_set_size_request (ahmed_radio_1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ahmed_radio_1), ahmed_radio_1_group);
  ahmed_radio_1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ahmed_radio_1));

  ahmed_raddio_0 = gtk_radio_button_new_with_mnemonic (NULL, _("etat 0"));
  gtk_widget_show (ahmed_raddio_0);
  gtk_fixed_put (GTK_FIXED (fixed1), ahmed_raddio_0, 608, 256);
  gtk_widget_set_size_request (ahmed_raddio_0, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ahmed_raddio_0), ahmed_radio_1_group);
  ahmed_radio_1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ahmed_raddio_0));

  button_Ajout_Annuler_GestCapt = gtk_button_new ();
  gtk_widget_show (button_Ajout_Annuler_GestCapt);
  gtk_fixed_put (GTK_FIXED (fixed1), button_Ajout_Annuler_GestCapt, 432, 328);
  gtk_widget_set_size_request (button_Ajout_Annuler_GestCapt, 100, 30);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button_Ajout_Annuler_GestCapt), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox17), label30, FALSE, FALSE, 0);

  button_Ajout_Ajouter_GestCapt = gtk_button_new ();
  gtk_widget_show (button_Ajout_Ajouter_GestCapt);
  gtk_fixed_put (GTK_FIXED (fixed1), button_Ajout_Ajouter_GestCapt, 192, 330);
  gtk_widget_set_size_request (button_Ajout_Ajouter_GestCapt, 100, 30);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_Ajout_Ajouter_GestCapt), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox1), label7, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ahmed_radio_1, "toggled",
                    G_CALLBACK (on_ahmed_radio_1_toggled),
                    NULL);
  g_signal_connect ((gpointer) ahmed_raddio_0, "toggled",
                    G_CALLBACK (on_ahmed_raddio_0_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_Ajout_Annuler_GestCapt, "clicked",
                    G_CALLBACK (on_button_Ajout_Annuler_GestCapt_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_Ajout_Ajouter_GestCapt, "clicked",
                    G_CALLBACK (on_button_Ajout_Ajouter_GestCapt_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter, Ajouter, "Ajouter");
  GLADE_HOOKUP_OBJECT (Ajouter, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Ajouter, entry_reference_GestCapt, "entry_reference_GestCapt");
  GLADE_HOOKUP_OBJECT (Ajouter, entry_Localisation_GestCapt, "entry_Localisation_GestCapt");
  GLADE_HOOKUP_OBJECT (Ajouter, entry_Valeur_Min_GestCapt, "entry_Valeur_Min_GestCapt");
  GLADE_HOOKUP_OBJECT (Ajouter, entry_Valeur_Max_GestCapt, "entry_Valeur_Max_GestCapt");
  GLADE_HOOKUP_OBJECT (Ajouter, image19, "image19");
  GLADE_HOOKUP_OBJECT (Ajouter, label4, "label4");
  GLADE_HOOKUP_OBJECT (Ajouter, label2, "label2");
  GLADE_HOOKUP_OBJECT (Ajouter, label3, "label3");
  GLADE_HOOKUP_OBJECT (Ajouter, ahmed_combobox1, "ahmed_combobox1");
  GLADE_HOOKUP_OBJECT (Ajouter, label5, "label5");
  GLADE_HOOKUP_OBJECT (Ajouter, label12, "label12");
  GLADE_HOOKUP_OBJECT (Ajouter, label11, "label11");
  GLADE_HOOKUP_OBJECT (Ajouter, ahmed_radio_1, "ahmed_radio_1");
  GLADE_HOOKUP_OBJECT (Ajouter, ahmed_raddio_0, "ahmed_raddio_0");
  GLADE_HOOKUP_OBJECT (Ajouter, button_Ajout_Annuler_GestCapt, "button_Ajout_Annuler_GestCapt");
  GLADE_HOOKUP_OBJECT (Ajouter, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Ajouter, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Ajouter, image17, "image17");
  GLADE_HOOKUP_OBJECT (Ajouter, label30, "label30");
  GLADE_HOOKUP_OBJECT (Ajouter, button_Ajout_Ajouter_GestCapt, "button_Ajout_Ajouter_GestCapt");
  GLADE_HOOKUP_OBJECT (Ajouter, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Ajouter, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Ajouter, image1, "image1");
  GLADE_HOOKUP_OBJECT (Ajouter, label7, "label7");

  return Ajouter;
}

GtkWidget*
create_interface (void)
{
  GtkWidget *interface;
  GtkWidget *fixed2;
  GtkWidget *treeview_affichage_GestCapt;
  GtkWidget *entry_interface_Rechercher_GestCapt;
  GtkWidget *image18;
  GtkWidget *sassi_buton_supp;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label27;
  GtkWidget *button_interface_supprimer_GestCapt;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label11;
  GtkWidget *button_affichage_trv;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label25;
  GtkWidget *button_interface_Modifier_GestCapt;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label10;
  GtkWidget *button_interface_Ajouter_GestCapt;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label9;
  GtkWidget *button_interface_Rechercher_GestCapt;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label12;
  GtkWidget *button1_deff;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label26;

  interface = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (interface, 850, 650);
  gtk_window_set_title (GTK_WINDOW (interface), _("Interface"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (interface), fixed2);
  gtk_widget_set_size_request (fixed2, 850, 528);

  treeview_affichage_GestCapt = gtk_tree_view_new ();
  gtk_widget_show (treeview_affichage_GestCapt);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview_affichage_GestCapt, 21, 314);
  gtk_widget_set_size_request (treeview_affichage_GestCapt, 808, 312);

  entry_interface_Rechercher_GestCapt = gtk_entry_new ();
  gtk_widget_show (entry_interface_Rechercher_GestCapt);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_interface_Rechercher_GestCapt, 176, 152);
  gtk_widget_set_size_request (entry_interface_Rechercher_GestCapt, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_interface_Rechercher_GestCapt), 8226);

  image18 = create_pixmap (interface, "1.png");
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (fixed2), image18, 0, 0);
  gtk_widget_set_size_request (image18, 850, 650);

  sassi_buton_supp = gtk_button_new ();
  gtk_widget_show (sassi_buton_supp);
  gtk_fixed_put (GTK_FIXED (fixed2), sassi_buton_supp, 592, 152);
  gtk_widget_set_size_request (sassi_buton_supp, 120, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (sassi_buton_supp), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox14), label27, FALSE, FALSE, 0);

  button_interface_supprimer_GestCapt = gtk_button_new ();
  gtk_widget_show (button_interface_supprimer_GestCapt);
  gtk_fixed_put (GTK_FIXED (fixed2), button_interface_supprimer_GestCapt, 624, 64);
  gtk_widget_set_size_request (button_interface_supprimer_GestCapt, 216, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_interface_supprimer_GestCapt), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Supprimer (double click)"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox5), label11, FALSE, FALSE, 0);

  button_affichage_trv = gtk_button_new ();
  gtk_widget_show (button_affichage_trv);
  gtk_fixed_put (GTK_FIXED (fixed2), button_affichage_trv, 312, 64);
  gtk_widget_set_size_request (button_affichage_trv, 112, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_affichage_trv), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox12), label25, FALSE, FALSE, 0);

  button_interface_Modifier_GestCapt = gtk_button_new ();
  gtk_widget_show (button_interface_Modifier_GestCapt);
  gtk_fixed_put (GTK_FIXED (fixed2), button_interface_Modifier_GestCapt, 184, 64);
  gtk_widget_set_size_request (button_interface_Modifier_GestCapt, 100, 30);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_interface_Modifier_GestCapt), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox4), label10, FALSE, FALSE, 0);

  button_interface_Ajouter_GestCapt = gtk_button_new ();
  gtk_widget_show (button_interface_Ajouter_GestCapt);
  gtk_fixed_put (GTK_FIXED (fixed2), button_interface_Ajouter_GestCapt, 55, 65);
  gtk_widget_set_size_request (button_interface_Ajouter_GestCapt, 100, 30);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_interface_Ajouter_GestCapt), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox3), label9, FALSE, FALSE, 0);

  button_interface_Rechercher_GestCapt = gtk_button_new ();
  gtk_widget_show (button_interface_Rechercher_GestCapt);
  gtk_fixed_put (GTK_FIXED (fixed2), button_interface_Rechercher_GestCapt, 55, 152);
  gtk_widget_set_size_request (button_interface_Rechercher_GestCapt, 100, 30);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_interface_Rechercher_GestCapt), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox6), label12, FALSE, FALSE, 0);

  button1_deff = gtk_button_new ();
  gtk_widget_show (button1_deff);
  gtk_fixed_put (GTK_FIXED (fixed2), button1_deff, 448, 64);
  gtk_widget_set_size_request (button1_deff, 165, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button1_deff), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Capteur deffectieux"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox13), label26, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_affichage_GestCapt, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) sassi_buton_supp, "clicked",
                    G_CALLBACK (on_sassi_buton_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_interface_supprimer_GestCapt, "clicked",
                    G_CALLBACK (on_button_interface_supprimer_GestCapt_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_affichage_trv, "clicked",
                    G_CALLBACK (on_button_affichage_trv_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_interface_Modifier_GestCapt, "clicked",
                    G_CALLBACK (on_button_interface_Modifier_GestCapt_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_interface_Ajouter_GestCapt, "clicked",
                    G_CALLBACK (on_button_interface_Ajouter_GestCapt_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_interface_Rechercher_GestCapt, "clicked",
                    G_CALLBACK (on_button_interface_Rechercher_GestCapt_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_deff, "clicked",
                    G_CALLBACK (on_button1_deff_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (interface, interface, "interface");
  GLADE_HOOKUP_OBJECT (interface, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (interface, treeview_affichage_GestCapt, "treeview_affichage_GestCapt");
  GLADE_HOOKUP_OBJECT (interface, entry_interface_Rechercher_GestCapt, "entry_interface_Rechercher_GestCapt");
  GLADE_HOOKUP_OBJECT (interface, image18, "image18");
  GLADE_HOOKUP_OBJECT (interface, sassi_buton_supp, "sassi_buton_supp");
  GLADE_HOOKUP_OBJECT (interface, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (interface, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (interface, image14, "image14");
  GLADE_HOOKUP_OBJECT (interface, label27, "label27");
  GLADE_HOOKUP_OBJECT (interface, button_interface_supprimer_GestCapt, "button_interface_supprimer_GestCapt");
  GLADE_HOOKUP_OBJECT (interface, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (interface, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (interface, image5, "image5");
  GLADE_HOOKUP_OBJECT (interface, label11, "label11");
  GLADE_HOOKUP_OBJECT (interface, button_affichage_trv, "button_affichage_trv");
  GLADE_HOOKUP_OBJECT (interface, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (interface, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (interface, image12, "image12");
  GLADE_HOOKUP_OBJECT (interface, label25, "label25");
  GLADE_HOOKUP_OBJECT (interface, button_interface_Modifier_GestCapt, "button_interface_Modifier_GestCapt");
  GLADE_HOOKUP_OBJECT (interface, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (interface, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (interface, image4, "image4");
  GLADE_HOOKUP_OBJECT (interface, label10, "label10");
  GLADE_HOOKUP_OBJECT (interface, button_interface_Ajouter_GestCapt, "button_interface_Ajouter_GestCapt");
  GLADE_HOOKUP_OBJECT (interface, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (interface, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (interface, image3, "image3");
  GLADE_HOOKUP_OBJECT (interface, label9, "label9");
  GLADE_HOOKUP_OBJECT (interface, button_interface_Rechercher_GestCapt, "button_interface_Rechercher_GestCapt");
  GLADE_HOOKUP_OBJECT (interface, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (interface, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (interface, image6, "image6");
  GLADE_HOOKUP_OBJECT (interface, label12, "label12");
  GLADE_HOOKUP_OBJECT (interface, button1_deff, "button1_deff");
  GLADE_HOOKUP_OBJECT (interface, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (interface, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (interface, image13, "image13");
  GLADE_HOOKUP_OBJECT (interface, label26, "label26");

  return interface;
}

GtkWidget*
create_ahmed_supprimer (void)
{
  GtkWidget *ahmed_supprimer;
  GtkWidget *Supprimer;
  GtkWidget *image20;
  GtkWidget *label6;
  GtkWidget *non_checkahmed;
  GtkWidget *ahmed_checkbutton1;
  GtkWidget *button_ok_supprimer;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label24;

  ahmed_supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ahmed_supprimer), _("Supprimer"));

  Supprimer = gtk_fixed_new ();
  gtk_widget_show (Supprimer);
  gtk_container_add (GTK_CONTAINER (ahmed_supprimer), Supprimer);

  image20 = create_pixmap (ahmed_supprimer, "455.png");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (Supprimer), image20, 0, 0);
  gtk_widget_set_size_request (image20, 704, 480);

  label6 = gtk_label_new (_("Voulez vous sur de supprimer ?"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (Supprimer), label6, 200, 40);
  gtk_widget_set_size_request (label6, 210, 30);

  non_checkahmed = gtk_check_button_new_with_mnemonic (_("annuler"));
  gtk_widget_show (non_checkahmed);
  gtk_fixed_put (GTK_FIXED (Supprimer), non_checkahmed, 384, 128);
  gtk_widget_set_size_request (non_checkahmed, 118, 24);

  ahmed_checkbutton1 = gtk_check_button_new_with_mnemonic (_("oui"));
  gtk_widget_show (ahmed_checkbutton1);
  gtk_fixed_put (GTK_FIXED (Supprimer), ahmed_checkbutton1, 136, 128);
  gtk_widget_set_size_request (ahmed_checkbutton1, 118, 24);

  button_ok_supprimer = gtk_button_new ();
  gtk_widget_show (button_ok_supprimer);
  gtk_fixed_put (GTK_FIXED (Supprimer), button_ok_supprimer, 224, 240);
  gtk_widget_set_size_request (button_ok_supprimer, 150, 30);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_ok_supprimer), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Ok"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox11), label24, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) non_checkahmed, "toggled",
                    G_CALLBACK (on_non_checkahmed_toggled),
                    NULL);
  g_signal_connect ((gpointer) ahmed_checkbutton1, "toggled",
                    G_CALLBACK (on_ahmed_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_ok_supprimer, "clicked",
                    G_CALLBACK (on_button_ok_supprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ahmed_supprimer, ahmed_supprimer, "ahmed_supprimer");
  GLADE_HOOKUP_OBJECT (ahmed_supprimer, Supprimer, "Supprimer");
  GLADE_HOOKUP_OBJECT (ahmed_supprimer, image20, "image20");
  GLADE_HOOKUP_OBJECT (ahmed_supprimer, label6, "label6");
  GLADE_HOOKUP_OBJECT (ahmed_supprimer, non_checkahmed, "non_checkahmed");
  GLADE_HOOKUP_OBJECT (ahmed_supprimer, ahmed_checkbutton1, "ahmed_checkbutton1");
  GLADE_HOOKUP_OBJECT (ahmed_supprimer, button_ok_supprimer, "button_ok_supprimer");
  GLADE_HOOKUP_OBJECT (ahmed_supprimer, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (ahmed_supprimer, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (ahmed_supprimer, image11, "image11");
  GLADE_HOOKUP_OBJECT (ahmed_supprimer, label24, "label24");

  return ahmed_supprimer;
}

GtkWidget*
create_Modification (void)
{
  GtkWidget *Modification;
  GtkWidget *Modifier;
  GtkWidget *entry_reference_Capteur_a_modifier_GestCapt;
  GtkWidget *entry_Nouveau_Type_GestCapt;
  GtkWidget *entry_Nouveau_localisation_GestCapt;
  GtkWidget *entry_Nouveau_Valeur_Min_GestCapt;
  GtkWidget *entry_Nouveau_Valeur_Max_GestCapt;
  GtkWidget *entry_nouveau_Etat_GestCapt;
  GtkWidget *image21;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *button_Modifier_OK_GestCapt;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label22;
  GtkWidget *button_Modifier_Retour_GestCapt;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label23;

  Modification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modification), _("Modifier"));

  Modifier = gtk_fixed_new ();
  gtk_widget_show (Modifier);
  gtk_container_add (GTK_CONTAINER (Modification), Modifier);

  entry_reference_Capteur_a_modifier_GestCapt = gtk_entry_new ();
  gtk_widget_show (entry_reference_Capteur_a_modifier_GestCapt);
  gtk_fixed_put (GTK_FIXED (Modifier), entry_reference_Capteur_a_modifier_GestCapt, 312, 48);
  gtk_widget_set_size_request (entry_reference_Capteur_a_modifier_GestCapt, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_reference_Capteur_a_modifier_GestCapt), 8226);

  entry_Nouveau_Type_GestCapt = gtk_entry_new ();
  gtk_widget_show (entry_Nouveau_Type_GestCapt);
  gtk_fixed_put (GTK_FIXED (Modifier), entry_Nouveau_Type_GestCapt, 312, 112);
  gtk_widget_set_size_request (entry_Nouveau_Type_GestCapt, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Nouveau_Type_GestCapt), 8226);

  entry_Nouveau_localisation_GestCapt = gtk_entry_new ();
  gtk_widget_show (entry_Nouveau_localisation_GestCapt);
  gtk_fixed_put (GTK_FIXED (Modifier), entry_Nouveau_localisation_GestCapt, 312, 184);
  gtk_widget_set_size_request (entry_Nouveau_localisation_GestCapt, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Nouveau_localisation_GestCapt), 8226);

  entry_Nouveau_Valeur_Min_GestCapt = gtk_entry_new ();
  gtk_widget_show (entry_Nouveau_Valeur_Min_GestCapt);
  gtk_fixed_put (GTK_FIXED (Modifier), entry_Nouveau_Valeur_Min_GestCapt, 312, 248);
  gtk_widget_set_size_request (entry_Nouveau_Valeur_Min_GestCapt, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Nouveau_Valeur_Min_GestCapt), 8226);

  entry_Nouveau_Valeur_Max_GestCapt = gtk_entry_new ();
  gtk_widget_show (entry_Nouveau_Valeur_Max_GestCapt);
  gtk_fixed_put (GTK_FIXED (Modifier), entry_Nouveau_Valeur_Max_GestCapt, 312, 304);
  gtk_widget_set_size_request (entry_Nouveau_Valeur_Max_GestCapt, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Nouveau_Valeur_Max_GestCapt), 8226);

  entry_nouveau_Etat_GestCapt = gtk_entry_new ();
  gtk_widget_show (entry_nouveau_Etat_GestCapt);
  gtk_fixed_put (GTK_FIXED (Modifier), entry_nouveau_Etat_GestCapt, 312, 360);
  gtk_widget_set_size_request (entry_nouveau_Etat_GestCapt, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nouveau_Etat_GestCapt), 8226);

  image21 = create_pixmap (Modification, "455.png");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (Modifier), image21, 0, 0);
  gtk_widget_set_size_request (image21, 700, 500);

  label7 = gtk_label_new (_("R\303\251ference Capteur \303\240 modifier"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (Modifier), label7, 72, 48);
  gtk_widget_set_size_request (label7, 220, 30);

  label8 = gtk_label_new (_("Nouveau Type"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (Modifier), label8, 80, 112);
  gtk_widget_set_size_request (label8, 100, 30);

  label9 = gtk_label_new (_("Nouveau localisation"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (Modifier), label9, 80, 184);
  gtk_widget_set_size_request (label9, 150, 30);

  label10 = gtk_label_new (_("Nouveau Valeur Min"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (Modifier), label10, 80, 248);
  gtk_widget_set_size_request (label10, 150, 30);

  label13 = gtk_label_new (_("Nouveau Valeur Max"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (Modifier), label13, 80, 304);
  gtk_widget_set_size_request (label13, 150, 30);

  label14 = gtk_label_new (_("Etat"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (Modifier), label14, 104, 368);
  gtk_widget_set_size_request (label14, 49, 17);

  button_Modifier_OK_GestCapt = gtk_button_new ();
  gtk_widget_show (button_Modifier_OK_GestCapt);
  gtk_fixed_put (GTK_FIXED (Modifier), button_Modifier_OK_GestCapt, 120, 456);
  gtk_widget_set_size_request (button_Modifier_OK_GestCapt, 66, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_Modifier_OK_GestCapt), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox9), label22, FALSE, FALSE, 0);

  button_Modifier_Retour_GestCapt = gtk_button_new ();
  gtk_widget_show (button_Modifier_Retour_GestCapt);
  gtk_fixed_put (GTK_FIXED (Modifier), button_Modifier_Retour_GestCapt, 328, 456);
  gtk_widget_set_size_request (button_Modifier_Retour_GestCapt, 74, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_Modifier_Retour_GestCapt), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox10), label23, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_Modifier_OK_GestCapt, "clicked",
                    G_CALLBACK (on_button_Modifier_OK_GestCapt_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_Modifier_Retour_GestCapt, "clicked",
                    G_CALLBACK (on_button_Modifier_Retour_GestCapt_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modification, Modification, "Modification");
  GLADE_HOOKUP_OBJECT (Modification, Modifier, "Modifier");
  GLADE_HOOKUP_OBJECT (Modification, entry_reference_Capteur_a_modifier_GestCapt, "entry_reference_Capteur_a_modifier_GestCapt");
  GLADE_HOOKUP_OBJECT (Modification, entry_Nouveau_Type_GestCapt, "entry_Nouveau_Type_GestCapt");
  GLADE_HOOKUP_OBJECT (Modification, entry_Nouveau_localisation_GestCapt, "entry_Nouveau_localisation_GestCapt");
  GLADE_HOOKUP_OBJECT (Modification, entry_Nouveau_Valeur_Min_GestCapt, "entry_Nouveau_Valeur_Min_GestCapt");
  GLADE_HOOKUP_OBJECT (Modification, entry_Nouveau_Valeur_Max_GestCapt, "entry_Nouveau_Valeur_Max_GestCapt");
  GLADE_HOOKUP_OBJECT (Modification, entry_nouveau_Etat_GestCapt, "entry_nouveau_Etat_GestCapt");
  GLADE_HOOKUP_OBJECT (Modification, image21, "image21");
  GLADE_HOOKUP_OBJECT (Modification, label7, "label7");
  GLADE_HOOKUP_OBJECT (Modification, label8, "label8");
  GLADE_HOOKUP_OBJECT (Modification, label9, "label9");
  GLADE_HOOKUP_OBJECT (Modification, label10, "label10");
  GLADE_HOOKUP_OBJECT (Modification, label13, "label13");
  GLADE_HOOKUP_OBJECT (Modification, label14, "label14");
  GLADE_HOOKUP_OBJECT (Modification, button_Modifier_OK_GestCapt, "button_Modifier_OK_GestCapt");
  GLADE_HOOKUP_OBJECT (Modification, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Modification, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Modification, image9, "image9");
  GLADE_HOOKUP_OBJECT (Modification, label22, "label22");
  GLADE_HOOKUP_OBJECT (Modification, button_Modifier_Retour_GestCapt, "button_Modifier_Retour_GestCapt");
  GLADE_HOOKUP_OBJECT (Modification, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Modification, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Modification, image10, "image10");
  GLADE_HOOKUP_OBJECT (Modification, label23, "label23");

  return Modification;
}

GtkWidget*
create_fenetre_captdeff (void)
{
  GtkWidget *fenetre_captdeff;
  GtkWidget *fixed3;
  GtkWidget *treeview1;
  GtkWidget *image22;
  GtkWidget *button1_retourcapt;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label29;
  GtkWidget *ahmedaffichagedeff;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label28;

  fenetre_captdeff = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_captdeff), _("window1"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (fenetre_captdeff), fixed3);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 40, 32);
  gtk_widget_set_size_request (treeview1, 464, 280);

  image22 = create_pixmap (fenetre_captdeff, "455.png");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed3), image22, 0, 0);
  gtk_widget_set_size_request (image22, 700, 500);

  button1_retourcapt = gtk_button_new ();
  gtk_widget_show (button1_retourcapt);
  gtk_fixed_put (GTK_FIXED (fixed3), button1_retourcapt, 392, 328);
  gtk_widget_set_size_request (button1_retourcapt, 112, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button1_retourcapt), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox16), label29, FALSE, FALSE, 0);

  ahmedaffichagedeff = gtk_button_new ();
  gtk_widget_show (ahmedaffichagedeff);
  gtk_fixed_put (GTK_FIXED (fixed3), ahmedaffichagedeff, 56, 336);
  gtk_widget_set_size_request (ahmedaffichagedeff, 96, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (ahmedaffichagedeff), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Affichier"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox15), label28, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button1_retourcapt, "clicked",
                    G_CALLBACK (on_button1_retourcapt_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmedaffichagedeff, "clicked",
                    G_CALLBACK (on_ahmedaffichagedeff_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_captdeff, fenetre_captdeff, "fenetre_captdeff");
  GLADE_HOOKUP_OBJECT (fenetre_captdeff, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (fenetre_captdeff, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (fenetre_captdeff, image22, "image22");
  GLADE_HOOKUP_OBJECT (fenetre_captdeff, button1_retourcapt, "button1_retourcapt");
  GLADE_HOOKUP_OBJECT (fenetre_captdeff, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (fenetre_captdeff, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (fenetre_captdeff, image16, "image16");
  GLADE_HOOKUP_OBJECT (fenetre_captdeff, label29, "label29");
  GLADE_HOOKUP_OBJECT (fenetre_captdeff, ahmedaffichagedeff, "ahmedaffichagedeff");
  GLADE_HOOKUP_OBJECT (fenetre_captdeff, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (fenetre_captdeff, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (fenetre_captdeff, image15, "image15");
  GLADE_HOOKUP_OBJECT (fenetre_captdeff, label28, "label28");

  return fenetre_captdeff;
}

